#开发环境

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://139.199.86.11:5432/cook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: admin
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
security:
  oauth2:
    client:
      client-id: cook
      client-secret: cookSecret
  basic:
  #关闭security
    enabled: false
